export const ProductsData = [
  {
    id: "1",
    name: "Apple Iphone 17",
    price: 75000,
    image: "/productImages/iphone 17.webp",
    description:
      "Meet the new iPhone 17. Designed with contoured edges, thinner borders, and durable materials like Ceramic Shield 2 on the front, it looks — and stays — beautiful. You can see and do more of everything you love on a 6.3-inch Super Retina XDR display.5 And enjoy smoother scrolling and more immersive gaming with ProMotion, with an adaptive refresh rate up to 120Hz. Take it for a spin.",
    category: "electronics",
    rating: 4.9,
    stock: 10,
    seller: "Apple",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "2",
    name: "Samsung Galaxy s25 ultra",
    price: 65000,
    image: "/productImages/samsung S25.jpeg",
    description:
      "The Samsung Galaxy S25 Ultra features a powerful Snapdragon 8 Elite processor, a vibrant 6.9-inch QHD+ display with a 120Hz refresh rate and Gorilla Glass Armor 2 for enhanced durability and reduced glare, and a versatile camera system led by a 200MP main sensor and a new 50MP ultra-wide lens. It boasts enhanced AI features through a Gemini/Bixby hybrid assistant ,a refined design with rounded corners and a titanium frame",
    category: "electronics",
    rating: 4.8,
    stock: 15,
    seller: "Samsung",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "3",
    name: "Playstation 5 ",
    price: 30000,
    image: "/productImages/ps5.jpg",
    description:
      "The PlayStation 5 (PS5) is Sony's powerful fifth-generation game console featuring an ultra-high-speed SSD for rapid load times, a custom CPU/GPU for stunning graphics and high frame rates up to 120fps, and support for advanced features like 4K resolution, ray tracing, haptic feedback, adaptive triggers, and 3D Audio for immersive gameplay. It offers backward compatibility with most PS4 games, a DualSense controller with tactile feedback, and access to a vast library of PlayStation games.",
    category: "electronics",
    rating: 4.7,
    stock: 10,
    seller: "Sony",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "4",
    name: "Xbox Series X",
    price: 25000,
    image: "/productImages/xbox-series-x.png",
    description:
      "The Xbox Series X is Microsoft's powerful, high-performance gaming console designed for an unparalleled next-generation experience , featuring a custom AMD processor, a 1TB SSD for fast loading, Quick Resume to switch between games instantly, DirectX ray tracing for realistic graphics, 4K resolution support, and backward compatibility with thousands of Xbox One, Xbox 360, and original Xbox games.  ",
    category: "electronics",
    rating: 4.6,
    stock: 10,
    seller: "Microsoft",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "5",
    image: "/productImages/Apple MacBook pro.jpeg",
    name: "MacBook Pro M4",
    price: 120000,
    category: "electronics",
    description: "The latest MacBook Pro with the powerful M4 chip.",
    rating: 4.9,
    stock: 10,
    seller: "Apple",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "6",
    name: "Sony Headset",
    image: "/productImages/Sony WH-1000XM4.avif",
    price: 1500,
    category: "electronics",
    description: "Sony WH-1000XM4 Wireless Noise-Cancelling Headphones.",
    rating: 4.8,
    stock: 10,
    seller: "Sony",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "7",
    name: "dell xps Laptop",
    image: "/productImages/dell xps.avif",
    price: 15000,
    category: "electronics",
    description:
      "Dell XPS laptop with high-resolution display and powerful performance.",
    rating: 4.5,
    stock: 15,
    seller: "Dell",
    createdAt: "2023-05-15T09:30:00Z",
    sales: 120,
  },
  {
    id: "8",
    name: "T-shirt",
    price: 500,
    image: "/productImages/t-shirt.jpg",
    description: "A comfortable cotton t-shirt.",
    category: "fashion",
    rating: 4.2,
    stock: 100,
    seller: "FashionBrand",
    createdAt: "2023-06-01T10:00:00Z",
    sales: 300,
  },
  {
    id: "9",
    name: "Jeans",
    price: 1200,
    image: "/productImages/jeans.jpg",
    description: "Stylish blue jeans.",
    category: "fashion",
    rating: 4.6,
    stock: 80,
    seller: "FashionBrand",
    createdAt: "2023-05-20T14:00:00Z",
    sales: 250,
  },
  {
    id: "10",
    name: "Organic Apples",
    price: 150,
    image: "/productImages/apples.jpg",
    description: "Fresh organic apples.",
    category: "grocery",
    rating: 4.8,
    stock: 200,
    seller: "FreshFarms",
    createdAt: "2023-06-10T08:00:00Z",
    sales: 500,
  },
  {
    id: "11",
    name: "Car Wax",
    price: 300,
    image: "/productImages/car-wax.jpg",
    description: "High-quality car wax for a brilliant shine.",
    category: "car-care",
    rating: 4.7,
    stock: 50,
    seller: "AutoShine",
    createdAt: "2023-04-25T11:20:00Z",
    sales: 150,
  },
  {
    id: "12",
    name: "The Great Gatsby",
    price: 250,
    image: "/productImages/gatsby.jpg",
    description: "A classic novel by F. Scott Fitzgerald.",
    category: "books",
    rating: 4.9,
    stock: 120,
    seller: "BookWorld",
    createdAt: "2023-03-10T18:45:00Z",
    sales: 400,
  },
];

export const categories = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    image: "HomePage/electronic-cat.png",
    description: "Latest gadgets and tech devices",
    color: "bg-yellow-400",
  },
  {
    id: 2,
    name: "Car Care",
    slug: "car-care",
    image: "HomePage/car-care.jpg",
    description: "Car Care Products – Shine, Protect & Refresh Your Ride",
    color: "bg-yellow-400",
  },
  {
    id: 3,
    name: "Books",
    slug: "books",
    image: "HomePage/books.png",
    description: "Books – Discover, Learn & Get Inspired",
    color: "bg-yellow-400",
  },
  {
    id: 4,
    name: "fashion",
    slug: "fashion",
    image: "HomePage/fashion.png",
    description: "Fashion – Style That Defines You",
    color: "bg-yellow-400",
  },
  {
    id: 5,
    name: "Grocery",
    slug: "grocery",
    image: "HomePage/Groceries-Banner.jpeg",
    description: "High-quality of grociries",
    color: "bg-yellow-400",
  },
];

export const getProductCategory = (categorySlug) => {
  return ProductsData.filter((product) => product.category === categorySlug);
};
export const getCategoryState = () => {
  return catrgories.map((category) => ({
    ...category,
    productCount: getProductCategory(category.slug).length,
  }));
};
